[package]
name = "lsp-translations"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-lsp = "0.14.1"
tokio = { version = "1.11.0", features = ["net", "macros", "rt-multi-thread", "io-util", "io-std"] }
serde_json = "1.0.67"

[dev-dependencies]
tower-test = "0.4.0"
