on: [push]

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os || 'ubuntu-latest'}}
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu,
            x86_64-apple-darwin,
            x86_64-pc-windows-gnu,
          ]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          - target: x86_64-pc-windows-gnu
            os: windows-2022

          - target: x86_64-apple-darwin
            os: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}

      - name: Run check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=${{matrix.target}}
          use-cross: ${{!matrix.os}}

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=${{matrix.target}}
          use-cross: ${{!matrix.os}}

  build:
    name: Build
    needs: [test]
    runs-on: ${{matrix.os || 'ubuntu-latest'}}
    strategy:
      fail-fast: false
      matrix:
        target: [
            aarch64-apple-darwin,
            # i686-apple-darwin,
            x86_64-apple-darwin,

            i686-pc-windows-msvc,
            x86_64-pc-windows-gnu,

            aarch64-unknown-linux-musl,
            i686-unknown-linux-musl,
            x86_64-unknown-linux-musl,
            armv7-unknown-linux-musleabihf,
            arm-unknown-linux-musleabi,
          ]
        include:
          - target: i686-pc-windows-msvc
            os: windows-2022
          - target: aarch64-apple-darwin
            os: macos-latest
          # - target: i686-apple-darwin
          #   os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}

      # Code from https://github.com/prisma/prisma-engines/blob/master/.github/workflows/build-apple-silicon.yml#L42-L56
      - if: matrix.target == 'aarch64-apple-darwin'
        run: xcodebuild -showsdks

      # Remove Xcode Command Line Tools so old version can not be used in build via https://github.com/prisma/prisma/issues/5245#issuecomment-864356168
      - if: matrix.target == 'aarch64-apple-darwin'
        run: sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*;

      # Activate newest available Xcode
      - if: matrix.target == 'aarch64-apple-darwin'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # Build with fancy params via https://github.com/shepmaster/rust/blob/silicon/silicon/README.md
      - if: matrix.target == 'aarch64-apple-darwin'
        run: |
          SDKROOT=$(xcrun --show-sdk-path)
          MACOSX_DEPLOYMENT_TARGET=$(xcrun --show-sdk-platform-version)

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
          use-cross: ${{!matrix.os}}

      - if: matrix.target == 'x86_64-pc-windows-gnu'
        name: "Zip files (Windows on Linux OS)"
        run: zip ${{ matrix.target }}.zip ./target/${{ matrix.target }}/release/lsp-translations.exe -j
      - if: matrix.os == 'windows-2022'
        name: "Zip files (Windows OS)"
        run: powershell Compress-Archive -Path ./target/${{ matrix.target }}/release/lsp-translations.exe -DestinationPath ./${{ matrix.target }}.zip
      - if: matrix.target != 'x86_64-pc-windows-gnu' && matrix.os != 'windows-2022'
        name: "Zip files (Linux and MacOS)"
        run: zip ${{ matrix.target }}.zip ./target/${{ matrix.target }}/release/lsp-translations -j
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.target }}.zip
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          release_branches: master
      - name: Download artifacts
        uses: actions/download-artifact@v2
        id: download
        with:
          path: target/release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{steps.download.outputs.download-path}}/*/*.zip
          fail_on_unmatched_files: true
          tag_name: ${{ steps.tag_version.outputs.new_tag || github.ref }}
          body: ${{ steps.tag_version.outputs.changelog }}
