on: [push]

name: CI

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: test

  build:
    name: Build
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          x86_64-pc-windows-gnu,
          aarch64-unknown-linux-gnu,
          armv7-unknown-linux-gnueabihf,
          i686-unknown-linux-gnu,
          i686-unknown-linux-musl,
          arm-unknown-linux-gnueabi,
          x86_64-unknown-linux-gnu,
          x86_64-unknown-linux-musl]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
          use-cross: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Target ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release

